// <auto-generated />
using System;
using ChequeVerification.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChequeVerification.Web.Migrations
{
    [DbContext(typeof(ChequeVerificationDbContext))]
    [Migration("20260901092814_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_AuditLog_CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLog", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.Cheque", b =>
                {
                    b.Property<int>("ChequeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChequeId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ChequeNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ImportedByUserId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1, "DF_Cheque_Status");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Cheque_UploadedAt");

                    b.HasKey("ChequeId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ImportedByUserId");

                    b.ToTable("Cheque", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_Customer_CreatedAt");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NationalId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CustomerId");

                    b.HasIndex(new[] { "CustomerNumber" }, "UQ_Customer_CustomerNumber")
                        .IsUnique();

                    b.ToTable("Customer", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.ExtractedSignature", b =>
                {
                    b.Property<int>("ExtractedSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtractedSignatureId"));

                    b.Property<int>("ChequeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExtractedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_ExtractedSignature_ExtractedAt");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ExtractedSignatureId");

                    b.HasIndex(new[] { "ChequeId" }, "UQ_ExtractedSignature_Cheque")
                        .IsUnique();

                    b.ToTable("ExtractedSignature", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.ReferenceSignature", b =>
                {
                    b.Property<int>("ReferenceSignatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReferenceSignatureId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_ReferenceSignature_CreatedAt");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("FileHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true, "DF_ReferenceSignature_IsActive");

                    b.HasKey("ReferenceSignatureId");

                    b.HasIndex("CustomerId");

                    b.ToTable("ReferenceSignature", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "Name" }, "UQ_Role_Name")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.SignatureComparison", b =>
                {
                    b.Property<int>("ComparisonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComparisonId"));

                    b.Property<int>("ExtractedSignatureId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBestMatch")
                        .HasColumnType("bit");

                    b.Property<int>("ReferenceSignatureId")
                        .HasColumnType("int");

                    b.Property<decimal>("SimilarityScore")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<int>("VerificationId")
                        .HasColumnType("int");

                    b.HasKey("ComparisonId");

                    b.HasIndex("ExtractedSignatureId");

                    b.HasIndex("ReferenceSignatureId");

                    b.HasIndex(new[] { "VerificationId", "ReferenceSignatureId" }, "UQ_SignatureComparison_ResultReference")
                        .IsUnique();

                    b.ToTable("SignatureComparison", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_User_CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1, "DF_User_Status");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ_User_Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.VerificationResult", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationId"));

                    b.Property<byte>("AutomaticDecision")
                        .HasColumnType("tinyint");

                    b.Property<int>("ChequeId")
                        .HasColumnType("int");

                    b.Property<byte?>("FinalDecision")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("LowerThresholdUsed")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ReviewerComment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("SimilarityScore")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal>("UpperThresholdUsed")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<DateTime>("VerifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysdatetime())", "DF_VerificationResult_VerifiedAt");

                    b.HasKey("VerificationId");

                    b.HasIndex("ChequeId");

                    b.HasIndex("ReviewedByUserId");

                    b.ToTable("VerificationResult", (string)null);
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.AuditLog", b =>
                {
                    b.HasOne("ChequeVerification.Web.Models.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLog_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.Cheque", b =>
                {
                    b.HasOne("ChequeVerification.Web.Models.Entities.Customer", "Customer")
                        .WithMany("Cheques")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Cheque_Customer");

                    b.HasOne("ChequeVerification.Web.Models.Entities.User", "ImportedByUser")
                        .WithMany("Cheques")
                        .HasForeignKey("ImportedByUserId")
                        .IsRequired()
                        .HasConstraintName("FK_Cheque_ImportedByUser");

                    b.Navigation("Customer");

                    b.Navigation("ImportedByUser");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.ExtractedSignature", b =>
                {
                    b.HasOne("ChequeVerification.Web.Models.Entities.Cheque", "Cheque")
                        .WithOne("ExtractedSignature")
                        .HasForeignKey("ChequeVerification.Web.Models.Entities.ExtractedSignature", "ChequeId")
                        .IsRequired()
                        .HasConstraintName("FK_ExtractedSignature_Cheque");

                    b.Navigation("Cheque");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.ReferenceSignature", b =>
                {
                    b.HasOne("ChequeVerification.Web.Models.Entities.Customer", "Customer")
                        .WithMany("ReferenceSignatures")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_ReferenceSignature_Customer");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.SignatureComparison", b =>
                {
                    b.HasOne("ChequeVerification.Web.Models.Entities.ExtractedSignature", "ExtractedSignature")
                        .WithMany("SignatureComparisons")
                        .HasForeignKey("ExtractedSignatureId")
                        .IsRequired()
                        .HasConstraintName("FK_SignatureComparison_ExtractedSignature");

                    b.HasOne("ChequeVerification.Web.Models.Entities.ReferenceSignature", "ReferenceSignature")
                        .WithMany("SignatureComparisons")
                        .HasForeignKey("ReferenceSignatureId")
                        .IsRequired()
                        .HasConstraintName("FK_SignatureComparison_ReferenceSignature");

                    b.HasOne("ChequeVerification.Web.Models.Entities.VerificationResult", "Verification")
                        .WithMany("SignatureComparisons")
                        .HasForeignKey("VerificationId")
                        .IsRequired()
                        .HasConstraintName("FK_SignatureComparison_Verification");

                    b.Navigation("ExtractedSignature");

                    b.Navigation("ReferenceSignature");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.User", b =>
                {
                    b.HasOne("ChequeVerification.Web.Models.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_User_Role");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.VerificationResult", b =>
                {
                    b.HasOne("ChequeVerification.Web.Models.Entities.Cheque", "Cheque")
                        .WithMany("VerificationResults")
                        .HasForeignKey("ChequeId")
                        .IsRequired()
                        .HasConstraintName("FK_VerificationResult_Cheque");

                    b.HasOne("ChequeVerification.Web.Models.Entities.User", "ReviewedByUser")
                        .WithMany("VerificationResults")
                        .HasForeignKey("ReviewedByUserId")
                        .HasConstraintName("FK_VerificationResult_Reviewer");

                    b.Navigation("Cheque");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.Cheque", b =>
                {
                    b.Navigation("ExtractedSignature");

                    b.Navigation("VerificationResults");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.Customer", b =>
                {
                    b.Navigation("Cheques");

                    b.Navigation("ReferenceSignatures");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.ExtractedSignature", b =>
                {
                    b.Navigation("SignatureComparisons");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.ReferenceSignature", b =>
                {
                    b.Navigation("SignatureComparisons");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Cheques");

                    b.Navigation("VerificationResults");
                });

            modelBuilder.Entity("ChequeVerification.Web.Models.Entities.VerificationResult", b =>
                {
                    b.Navigation("SignatureComparisons");
                });
#pragma warning restore 612, 618
        }
    }
}
